// Workflow YAML templates and README generation

import type { LLMProvider, Language, Theme } from "../../../types.js";

// ── Constants ────────────────────────────────────────────────

export const LLM_SECRET_NAMES: Record<string, string> = {
  openai: "OPENAI_API_KEY",
  anthropic: "ANTHROPIC_API_KEY",
  gemini: "GEMINI_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
  groq: "GROQ_API_KEY",
  grok: "GROK_API_KEY",
};

const LLM_API_KEY_INPUT_NAMES: Record<string, string> = {
  openai: "openai-api-key",
  anthropic: "anthropic-api-key",
  gemini: "gemini-api-key",
  openrouter: "openrouter-api-key",
  groq: "groq-api-key",
  grok: "grok-api-key",
};

// ── Cron calculation from timezone ───────────────────────────
// Daily fetch should run at midnight in the user's timezone.
// GitHub Actions cron is always UTC, so we calculate the offset.

export const midnightCronUTC = (timezone: string): string => {
  // Use Jan 1 (standard time) to avoid DST-dependent offset.
  // During DST the cron fires ~1h late (e.g. 01:00 local), which is safe
  // because daily-fetch resolves "yesterday" from the local date.
  // The opposite (firing 1h early = 23:00 the previous day) would shift
  // the local date backward and collect the wrong day.
  const jan1 = new Date(new Date().getFullYear(), 0, 1, 0, 0, 0);
  const utcMidnight = new Date(
    jan1.toLocaleString("en-US", { timeZone: "UTC" }),
  );
  const localMidnight = new Date(
    jan1.toLocaleString("en-US", { timeZone: timezone }),
  );
  const offsetMinutes = Math.round(
    (utcMidnight.getTime() - localMidnight.getTime()) / 60000,
  );
  const utcHour = ((offsetMinutes / 60 + 24) % 24) | 0;
  const utcMinute = ((offsetMinutes % 60) + 60) % 60;
  return `${utcMinute} ${utcHour} * * *`;
};

// ── Workflow YAML template ───────────────────────────────────

export type WorkflowOpts = {
  username: string;
  language: Language;
  timezone: string;
  siteTitle: string;
  theme: Theme;
  llmProvider?: LLMProvider;
  llmModel?: string;
  llmSecretName?: string;
};

export const buildDailyWorkflow = (opts: WorkflowOpts): string => {
  const cron = midnightCronUTC(opts.timezone);

  return `# Generated by: github-weekly-reporter setup
# Docs: https://github.com/deariary/github-weekly-reporter

name: Daily Fetch

on:
  schedule:
    - cron: '${cron}'  # midnight ${opts.timezone}
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: deariary/github-weekly-reporter@main
        with:
          github-token: \${{ secrets.GH_PAT }}
          username: '${opts.username}'
          mode: 'daily'
          language: '${opts.language}'
          timezone: '${opts.timezone}'
`;
};

export const weeklyCronUTC = (timezone: string): string => {
  // Weekly report runs Thursday morning, 1 hour after daily fetch.
  // Because cron is in UTC, the UTC day-of-week may differ from the
  // local day-of-week for timezones with positive offsets.
  const dailyCron = midnightCronUTC(timezone);
  const [minute, hour] = dailyCron.split(" ").map(Number);
  const weeklyHour = (hour + 1) % 24;
  const jan1 = new Date(new Date().getFullYear(), 0, 1, 0, 0, 0);
  const utcMidnight = new Date(
    jan1.toLocaleString("en-US", { timeZone: "UTC" }),
  );
  const localMidnight = new Date(
    jan1.toLocaleString("en-US", { timeZone: timezone }),
  );
  const offsetMinutes = Math.round(
    (localMidnight.getTime() - utcMidnight.getTime()) / 60000,
  );
  // Local Thursday 01:00 is 60 minutes after Thursday 00:00 local.
  // Cron DOW: 0=Sunday … 4=Thursday
  const utcMinutesFromThursdayStart = 60 - offsetMinutes;
  const dayShift = Math.floor(utcMinutesFromThursdayStart / (24 * 60));
  const utcDow = (((4 + dayShift) % 7) + 7) % 7;
  return `${minute} ${weeklyHour} * * ${utcDow}`;
};

export const buildWeeklyWorkflow = (opts: WorkflowOpts): string => {
  const weeklyCron = weeklyCronUTC(opts.timezone);

  const llmInputs =
    opts.llmProvider && opts.llmModel && opts.llmSecretName
      ? `          llm-provider: '${opts.llmProvider}'
          llm-model: '${opts.llmModel}'
          ${LLM_API_KEY_INPUT_NAMES[opts.llmProvider]}: \${{ secrets.${opts.llmSecretName} }}`
      : "";

  return `# Generated by: github-weekly-reporter setup
# Docs: https://github.com/deariary/github-weekly-reporter

name: Weekly Report

on:
  schedule:
    - cron: '${weeklyCron}'  # Thursday morning, 1 hour after daily fetch (${opts.timezone})
  workflow_dispatch:
    inputs:
      date:
        description: 'Target date (YYYY-MM-DD, default: today)'
        required: false
        type: string

permissions:
  contents: write
  pages: write

env:
  SITE_TITLE: '${opts.siteTitle}'

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: deariary/github-weekly-reporter@main
        with:
          github-token: \${{ secrets.GH_PAT }}
          username: '${opts.username}'
          mode: 'weekly'
          language: '${opts.language}'
          timezone: '${opts.timezone}'
          theme: '${opts.theme}'
          date: \${{ inputs.date }}
${llmInputs}
`;
};

// ── README template ──────────────────────────────────────────

export const buildReadme = (opts: {
  siteTitle: string;
  username: string;
  repo: string;
  pagesUrl: string;
  language: Language;
  timezone: string;
  theme: Theme;
  llmProvider?: LLMProvider;
  llmModel?: string;
}): string => {
  const displayTitle = opts.siteTitle.replace(/\\n/g, " ");
  return `# ${displayTitle}

This repository is generated and updated by [github-weekly-reporter](https://github.com/deariary/github-weekly-reporter).

Every week, GitHub Actions collects my activity (commits, PRs, reviews), an LLM writes a narrative summary, and the result is published as a blog-style report page and an animated profile card.

## Live Reports

${opts.pagesUrl}

## Profile Card

<a href="https://github.com/${opts.repo}">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="${opts.pagesUrl}/card-dark.svg" />
    <source media="(prefers-color-scheme: light)" srcset="${opts.pagesUrl}/card.svg" />
    <img alt="Weekly Report" src="${opts.pagesUrl}/card.svg" height="48" />
  </picture>
</a>

Add this to your [GitHub Profile README](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme):

\`\`\`html
<a href="https://github.com/${opts.repo}">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="${opts.pagesUrl}/card-dark.svg" />
    <source media="(prefers-color-scheme: light)" srcset="${opts.pagesUrl}/card.svg" />
    <img alt="Weekly Report" src="${opts.pagesUrl}/card.svg" height="48" />
  </picture>
</a>
\`\`\`

## How It Works

1. **Daily** (automatic): A scheduled workflow collects your GitHub events at midnight (${opts.timezone}).
2. **Weekly** (manual): Trigger the workflow with \`mode: weekly\` from the [Actions tab](https://github.com/${opts.repo}/actions) to generate a full report${opts.llmProvider ? " with AI narrative" : ""}.
3. The report is deployed to GitHub Pages automatically.

## Configuration

Edit \`.github/workflows/weekly-report.yml\` to change:

| Setting | Current | Description |
|---------|---------|-------------|
| \`username\` | \`${opts.username}\` | GitHub user to report on |
| \`language\` | \`${opts.language}\` | Report language (en, ja, zh-CN, zh-TW, ko, es, fr, de, pt, ru) |
| \`timezone\` | \`${opts.timezone}\` | IANA timezone for date calculations |
| \`theme\` | \`${opts.theme}\` | Report theme (brutalist, minimal, editorial, swiss) |
| \`SITE_TITLE\` | \`${displayTitle}\` | Site title in the header and hero |
${opts.llmProvider ? `| \`llm-provider\` | \`${opts.llmProvider}\` | LLM provider for AI narrative |\n| \`llm-model\` | \`${opts.llmModel}\` | Model name |\n` : ""}
## Base URL

The report's canonical URL, OG images, and sitemap are generated using \`BASE_URL\`.
By default this is derived automatically from the repository name:

\`\`\`
https://${opts.repo.split("/")[0]}.github.io/${opts.repo.split("/")[1]}
\`\`\`

If you use a **custom domain**, add \`BASE_URL\` to the workflow env:

\`\`\`yaml
env:
  SITE_TITLE: '${opts.siteTitle}'
  BASE_URL: 'https://your-custom-domain.com'
\`\`\`

Then configure the custom domain in **Settings > Pages > Custom domain**.

## Changing the LLM API Key

1. Go to **Settings > Secrets and variables > Actions**
2. Update the \`${opts.llmProvider ? LLM_SECRET_NAMES[opts.llmProvider] : "LLM_API_KEY"}\` secret

## Manual Report Generation

Go to [Actions](https://github.com/${opts.repo}/actions), click **Weekly Report**, then **Run workflow** with \`mode: weekly\`.

---

Supported by [deariary](https://deariary.com)
`;
};
