// Workflow YAML templates and README generation

import type { LLMProvider, Language, Theme } from "../../../types.js";

// ── Constants ────────────────────────────────────────────────

export const LLM_SECRET_NAMES: Record<string, string> = {
  openai: "OPENAI_API_KEY",
  anthropic: "ANTHROPIC_API_KEY",
  gemini: "GEMINI_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
  groq: "GROQ_API_KEY",
  grok: "GROK_API_KEY",
};

const LLM_API_KEY_INPUT_NAMES: Record<string, string> = {
  openai: "openai-api-key",
  anthropic: "anthropic-api-key",
  gemini: "gemini-api-key",
  openrouter: "openrouter-api-key",
  groq: "groq-api-key",
  grok: "grok-api-key",
};

// ── Cron calculation from timezone ───────────────────────────
// GitHub Actions cron is always UTC. Use the least-positive offset observed
// across January/July and schedule after local midnight at that offset. During
// DST the same UTC cron runs later, never on the preceding local date.

const offsetMinutesAt = (timezone: string, date: Date): number => {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  }).formatToParts(date);
  const value = (type: Intl.DateTimeFormatPartTypes): number =>
    Number(parts.find((part) => part.type === type)?.value ?? 0);
  const localAsUtc = Date.UTC(
    value("year"),
    value("month") - 1,
    value("day"),
    value("hour"),
    value("minute"),
    value("second"),
  );
  return Math.round((localAsUtc - date.getTime()) / 60000);
};

const stableOffsets = (timezone: string): number[] => {
  const year = new Date().getUTCFullYear();
  return [
    offsetMinutesAt(timezone, new Date(Date.UTC(year, 0, 1, 12))),
    offsetMinutesAt(timezone, new Date(Date.UTC(year, 6, 1, 12))),
  ];
};

const cronTimeForLocalHour = (
  timezone: string,
  localHour: number,
): { minute: number; hour: number; dayShift: number } => {
  const minimumOffset = Math.min(...stableOffsets(timezone));
  const utcMinutes = localHour * 60 - minimumOffset;
  const dayShift = Math.floor(utcMinutes / (24 * 60));
  const minuteOfDay = ((utcMinutes % (24 * 60)) + 24 * 60) % (24 * 60);
  return {
    minute: minuteOfDay % 60,
    hour: Math.floor(minuteOfDay / 60),
    dayShift,
  };
};

export const midnightCronUTC = (timezone: string): string => {
  const { minute, hour, dayShift } = cronTimeForLocalHour(timezone, 1);
  const utcWeekdays = dayShift < 0 ? "0-4" : "1-5";
  return `${minute} ${hour} * * ${utcWeekdays}`;
};

// ── Workflow YAML template ───────────────────────────────────

export type WorkflowOpts = {
  username: string;
  language: Language;
  timezone: string;
  siteTitle: string;
  theme: Theme;
  llmProvider?: LLMProvider;
  llmModel?: string;
  llmSecretName?: string;
};

export const buildDailyWorkflow = (opts: WorkflowOpts): string => {
  const cron = midnightCronUTC(opts.timezone);
  const llmInputs =
    opts.llmProvider && opts.llmModel && opts.llmSecretName
      ? `          llm-provider: '${opts.llmProvider}'
          llm-model: '${opts.llmModel}'
          ${LLM_API_KEY_INPUT_NAMES[opts.llmProvider]}: \${{ secrets.${opts.llmSecretName} }}`
      : "";

  return `# Generated by: github-weekly-reporter setup
# Docs: https://github.com/myriadas-clees/github-weekly-reporter

name: Daily Report

on:
  schedule:
    - cron: '${cron}'  # DST-safe, after midnight ${opts.timezone}
  workflow_dispatch:
    inputs:
      date:
        description: 'Report date (YYYY-MM-DD, default: previous workday)'
        required: false
        type: string

permissions:
  contents: write
  pages: write

env:
  SITE_TITLE: '${opts.siteTitle}'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: myriadas-clees/github-weekly-reporter@main
        with:
          github-token: \${{ secrets.GH_PAT }}
          username: '${opts.username}'
          mode: 'daily'
          language: '${opts.language}'
          timezone: '${opts.timezone}'
          theme: '${opts.theme}'
          date: \${{ inputs.date }}
${llmInputs}
`;
};

export const weeklyCronUTC = (timezone: string): string => {
  const { minute, hour, dayShift } = cronTimeForLocalHour(timezone, 2);
  const utcDow = (((4 + dayShift) % 7) + 7) % 7;
  return `${minute} ${hour} * * ${utcDow}`;
};

export const buildWeeklyWorkflow = (opts: WorkflowOpts): string => {
  const weeklyCron = weeklyCronUTC(opts.timezone);

  const llmInputs =
    opts.llmProvider && opts.llmModel && opts.llmSecretName
      ? `          llm-provider: '${opts.llmProvider}'
          llm-model: '${opts.llmModel}'
          ${LLM_API_KEY_INPUT_NAMES[opts.llmProvider]}: \${{ secrets.${opts.llmSecretName} }}`
      : "";

  return `# Generated by: github-weekly-reporter setup
# Docs: https://github.com/myriadas-clees/github-weekly-reporter

name: Weekly Report

on:
  schedule:
    - cron: '${weeklyCron}'  # Thursday morning, 1 hour after daily fetch (${opts.timezone})
  workflow_dispatch:
    inputs:
      date:
        description: 'Target date (YYYY-MM-DD, default: today)'
        required: false
        type: string

permissions:
  contents: write
  pages: write

env:
  SITE_TITLE: '${opts.siteTitle}'

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: myriadas-clees/github-weekly-reporter@main
        with:
          github-token: \${{ secrets.GH_PAT }}
          username: '${opts.username}'
          mode: 'weekly'
          language: '${opts.language}'
          timezone: '${opts.timezone}'
          theme: '${opts.theme}'
          date: \${{ inputs.date }}
${llmInputs}
`;
};

// ── README template ──────────────────────────────────────────

export const buildReadme = (opts: {
  siteTitle: string;
  username: string;
  repo: string;
  pagesUrl: string;
  language: Language;
  timezone: string;
  theme: Theme;
  llmProvider?: LLMProvider;
  llmModel?: string;
}): string => {
  const displayTitle = opts.siteTitle.replace(/\\n/g, " ");
  return `# ${displayTitle}

This repository is generated and updated by [github-weekly-reporter](https://github.com/myriadas-clees/github-weekly-reporter).

Every morning, GitHub Actions collects the previous day's activity (commits, PRs, reviews), writes a narrative summary, and publishes a report page and animated profile card.

## Live Reports

${opts.pagesUrl}

## Profile Card

<a href="https://github.com/${opts.repo}">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="${opts.pagesUrl}/card-dark.svg" />
    <source media="(prefers-color-scheme: light)" srcset="${opts.pagesUrl}/card.svg" />
    <img alt="Daily Report" src="${opts.pagesUrl}/card.svg" height="48" />
  </picture>
</a>

Add this to your [GitHub Profile README](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme):

\`\`\`html
<a href="https://github.com/${opts.repo}">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="${opts.pagesUrl}/card-dark.svg" />
    <source media="(prefers-color-scheme: light)" srcset="${opts.pagesUrl}/card.svg" />
    <img alt="Daily Report" src="${opts.pagesUrl}/card.svg" height="48" />
  </picture>
</a>
\`\`\`

## How It Works

1. **Daily** (automatic): A scheduled workflow collects the previous completed calendar day in ${opts.timezone}.
2. It generates a stakeholder summary${opts.llmProvider ? " with an optional AI narrative" : ""} and renders the report.
3. The report is deployed to GitHub Pages automatically under \`YYYY/MM/DD/\`.

## Configuration

Edit \`.github/workflows/daily-report.yml\` to change:

| Setting | Current | Description |
|---------|---------|-------------|
| \`username\` | \`${opts.username}\` | GitHub user to report on |
| \`language\` | \`${opts.language}\` | Report language (en, ja, zh-CN, zh-TW, ko, es, fr, de, pt, ru) |
| \`timezone\` | \`${opts.timezone}\` | IANA timezone for date calculations |
| \`theme\` | \`${opts.theme}\` | Report theme (brutalist, minimal, editorial, swiss) |
| \`SITE_TITLE\` | \`${displayTitle}\` | Site title in the header and hero |
${opts.llmProvider ? `| \`llm-provider\` | \`${opts.llmProvider}\` | LLM provider for AI narrative |\n| \`llm-model\` | \`${opts.llmModel}\` | Model name |\n` : ""}
## Base URL

The report's canonical URL, OG images, and sitemap are generated using \`BASE_URL\`.
By default this is derived automatically from the repository name:

\`\`\`
https://${opts.repo.split("/")[0]}.github.io/${opts.repo.split("/")[1]}
\`\`\`

If you use a **custom domain**, add \`BASE_URL\` to the workflow env:

\`\`\`yaml
env:
  SITE_TITLE: '${opts.siteTitle}'
  BASE_URL: 'https://your-custom-domain.com'
\`\`\`

Then configure the custom domain in **Settings > Pages > Custom domain**.

## Changing the LLM API Key

1. Go to **Settings > Secrets and variables > Actions**
2. Update the \`${opts.llmProvider ? LLM_SECRET_NAMES[opts.llmProvider] : "LLM_API_KEY"}\` secret

## Manual Report Generation

Go to [Actions](https://github.com/${opts.repo}/actions), click **Daily Report**, then **Run workflow**. Set \`date\` to regenerate a specific day.

---

Supported by [deariary](https://deariary.com)
`;
};
